sudo: required
services:
  - docker

before_install:
  - docker build -t ccccc170/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true ccccc170/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-eu-west-2-516064081160"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"